version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: jason1653
      MYSQL_DATABASE: jason
      MYSQL_USER: jason
      MYSQL_PASSWORD: jason1653
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: